excel_svr/excel_srvr/urls.py
from django.contrib import admin
from django.urls import path, include
from xl_calculation import views
urlpatterns = [
    path('',views.index,name='index'),
    path('xl_calculation/', include('xl_calculation.urls')),
    path('admin/', admin.site.urls),
]

excel_svr/xl_calculation/urls.py
from django.urls import path
from . import views

app_name = "xl_calculation"

urlpatterns = [
    path('', views.index, name='index'),
    path('download', views.download, name='download'),
]

excel_svr/xl_calculation/models.py
from django.db import models

# Create your models here.

excel_svr/xl_calculation/oldviews/views.py
from django.shortcuts import render
import openpyxl

def index(request):
    if "GET" == request.method:
        return render(request, 'xl_calculation/index.html', {})
    else:
        excel_file = request.FILES["excel_file"]

        wb = openpyxl.load_workbook(excel_file)

        # get all sheets
        sheets = wb.sheetnames
        print(sheets)

        # get a particular sheet
        worksheet = wb["Sheet1"]
        print(worksheet)

        #getting active sheet
        active_sheet = wb.active
        print(active_sheet)

        #reading a cell
        print(worksheet["A1"].value)

        #i terating over the rows and getting
        # value from each cell in row
        excel_data = list()

        for row in worksheet.iter_rows():
            row_data = list()
            for cell in row:
                row_data.append(str(cell.value))
                print(cell.value)
            excel_data.append(row_data)

        return render(request, "xl_calculation/index.html", {"excel_data":excel_data})

excel_svr/xl_calculation/views.py
from django.shortcuts import render
from django.conf import settings
from django.http import HttpResponse, Http404
from django.shortcuts import render
import openpyxl
import os
from xl_calculation.staffNoWait import computeNoWait

fn = ''

def download(request):
    global fn
    #Only run if the file was already upload
    if fn == '':
        raise Http404

    with open(fn, 'rb') as fh:
        response = HttpResponse(fh.read(), content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
        response['Content-Disposition'] = f'attachment; filename={os.path.basename(fn)}' # name it after the original file title
        fn = ''
        return response
    

def index(request):
    global fn
    if "GET" == request.method:
        return render(request, 'xl_calculation/index.html', {})
    else:
        excel_file = request.FILES["excel_file"]
        print(excel_file)
        wb = openpyxl.load_workbook(excel_file)
        
        print(type(str(excel_file)))
        # get all sheets
        sheets = wb.sheetnames
        print(sheets)

        # get a particular sheet
        worksheet = wb["Sheet1"]
        print(worksheet)

        #getting active sheet
        active_sheet = wb.active
        print(active_sheet)

        #reading a cell
        print(worksheet["A1"].value)

        #   numClassrooms = Number of classrooms                                       
        #   totalAtRiskStu = Total number of at risk students                            
        #   numStuPerTeacherOrAide = T2 Lite: Number of students per teacher or aide           
        #   probRespond = T2 Lite: Probability respond to T2 Lite                      
        #   numStuPerPsychologist = Evaluation: Number of students per psychologist            
        #   numStuPerInterventionist = T2 Heavy: Number of students per interventionist  

        numClassrooms = int(worksheet["F7"].value) 
        totalAtRiskStu = int(worksheet["F8"].value) 
        numStuPerTeacherOrAide = int(worksheet["F9"].value) 
        probRespond = float(worksheet["F10"].value) 
        numStuPerPsychologist = int(worksheet["F11"].value) 
        numStuPerInterventionist = int(worksheet["F12"].value) 

        # Using the function compuNoWait of the staffNoWait.py file
        numAides, numPsychologists, numInterventionists =                            \
        computeNoWait(numClassrooms, totalAtRiskStu, numStuPerTeacherOrAide,         \
            probRespond, numStuPerPsychologist, numStuPerInterventionist)

        # Placing the answer in the space of the answer
        worksheet['F15'] = numAides
        worksheet['F16'] = numPsychologists
        worksheet['F17'] = numInterventionists
        
        # Get file name of the file upload
        basename = os.path.basename(str(excel_file))
        #Add the complete file to the path files 
        fn = "files/" +basename 
        print(fn)
        # save file xlsx with the solution"
        wb.save(fn)

        excel_data = list()

        for row in worksheet.iter_rows():
            row_data = list()
            for cell in row:
                if cell.value == None: # if the cell is empty so replace it to a whitespace string
                    cell.value = ""
                row_data.append(str(cell.value))
                print(cell.value)
            excel_data.append(row_data)


        return render(request, "xl_calculation/index.html", {"excel_data":excel_data,"created":True})

excel_svr/xl_calculation/templates/xl_calculation/index.html
<html>
    <head>
        <title>
            Excel file upload and processing : Django Example : ThePythonDjango.Com
        </title>
    </head>
    <body style="margin-top: 30px;margin-left: 30px;">
        <h1>No Wait Model</h1>
        <form action="{% url "xl_calculation:index" %}" method="post" enctype="multipart/form-data" >
            {% csrf_token %}
            <input type="file"
                   title="Upload excel file"
                   name="excel_file"
                   style="border: 1px solid black; padding: 5px;"
                   required="required">
            <p>
            <input type="submit"
                   value="Upload"
                   style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">
        </form>

        <form action="{% url "xl_calculation:download" %}" method="post" enctype="multipart/form-data", name="downloadForm" style="display:none;">
            {% csrf_token %}
            <!-- <input type="file"
                   title="Upload excel file"
                   name="excel_file"
                   style="border: 1px solid black; padding: 5px;"
                   required="required"> -->
            <p>
            <input type="submit"
                   value="Download"
                   style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">
        </form>

        <p></p>
        <hr>

        {% for row in excel_data %}
            {% for cell in row %}
                {{ cell }}&nbsp;&nbsp;
            {% endfor %}
            <br>
        {% endfor %}
        {% if created %}
        <script>
            document.forms['downloadForm'].submit()
        </script>
                
        
           
        {% endif %}
    </body>
</html>

excel_svr/xl_calculation/templates/xl_calculation/master html/index.html
<html>
    <head>
        <title>
            Excel file upload and processing : Django Example : ThePythonDjango.Com
        </title>
    </head>
    <body style="margin-top: 30px;margin-left: 30px;">
        <form action="{% url "xl_calculation:index" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file"
                   title="Upload excel file"
                   name="excel_file"
                   style="border: 1px solid black; padding: 5px;"
                   required="required">
            <p>
            <input type="submit"
                   value="Upload"
                   style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">
        </form>

        <p></p>
        <hr>

        {% for row in excel_data %}
            {% for cell in row %}
                {{ cell }}&nbsp;&nbsp;
            {% endfor %}
            <br>
        {% endfor %}
    </body>
</html>